"""empty message

Revision ID: 5d504d2bc759
Revises: 
Create Date: 2021-04-20 11:34:22.826258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d504d2bc759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('path', 'end',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('path', 'end',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
