"""empty message

Revision ID: 911218376fb5
Revises: 5d504d2bc759
Create Date: 2021-04-20 12:21:23.981395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911218376fb5'
down_revision = '5d504d2bc759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('latitude_2', sa.Float(precision=10, asdecimal=20), nullable=False))
    op.add_column('node', sa.Column('longitude_2', sa.Float(precision=10, asdecimal=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'longitude_2')
    op.drop_column('node', 'latitude_2')
    # ### end Alembic commands ###
