"""empty message

Revision ID: 93a064debac2
Revises: 
Create Date: 2021-04-29 16:26:18.552854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a064debac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address1', sa.Text(), nullable=True),
    sa.Column('address2', sa.Text(), nullable=True),
    sa.Column('address3', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('b_type', sa.String(length=20), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('building_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('map_areas',
    sa.Column('map_area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude_1', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_1', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('latitude_2', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_2', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('latitude_3', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_3', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('latitude_4', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_4', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('map_area_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude_1', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_1', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('latitude_2', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude_2', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('map_zones',
    sa.Column('map_zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('map_area', sa.Integer(), nullable=False),
    sa.Column('latitude_1', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_1', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('latitude_2', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_2', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('latitude_3', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_3', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('latitude_4', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude_4', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['map_area'], ['map_areas.map_area_id'], ),
    sa.PrimaryKeyConstraint('map_zone_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('paths',
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_area', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['end'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['map_area'], ['map_areas.map_area_id'], ),
    sa.ForeignKeyConstraint(['start'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('path_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('starting_points',
    sa.Column('sp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('map_area', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['map_area'], ['map_areas.map_area_id'], ),
    sa.PrimaryKeyConstraint('sp_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('object_detection_objects',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('object_name', sa.String(length=200), nullable=False),
    sa.Column('map_zone', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.ForeignKeyConstraint(['map_zone'], ['map_zones.map_zone_id'], ),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('object_name')
    )
    op.create_table('path_building_connections',
    sa.Column('path_building_connection_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Integer(), nullable=False),
    sa.Column('stop_node', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.ForeignKeyConstraint(['path'], ['paths.path_id'], ),
    sa.ForeignKeyConstraint(['stop_node'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('path_building_connection_id')
    )
    op.create_table('path_connections',
    sa.Column('path_connection_id', sa.Integer(), nullable=False),
    sa.Column('path1', sa.Integer(), nullable=False),
    sa.Column('path2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path1'], ['paths.path_id'], ),
    sa.ForeignKeyConstraint(['path2'], ['paths.path_id'], ),
    sa.PrimaryKeyConstraint('path_connection_id')
    )
    op.create_table('path_starting_point_connections',
    sa.Column('path_building_connection_id', sa.Integer(), nullable=False),
    sa.Column('starting_point_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path'], ['paths.path_id'], ),
    sa.ForeignKeyConstraint(['starting_point_id'], ['starting_points.sp_id'], ),
    sa.PrimaryKeyConstraint('path_building_connection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('path_starting_point_connections')
    op.drop_table('path_connections')
    op.drop_table('path_building_connections')
    op.drop_table('object_detection_objects')
    op.drop_table('starting_points')
    op.drop_table('paths')
    op.drop_table('map_zones')
    op.drop_table('events')
    op.drop_table('nodes')
    op.drop_table('map_areas')
    op.drop_table('buildings')
    # ### end Alembic commands ###
