"""empty message

Revision ID: 964b6d8f0372
Revises: 911218376fb5
Create Date: 2021-04-20 12:24:04.538152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964b6d8f0372'
down_revision = '911218376fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('latitude_2', sa.Float(precision=10, asdecimal=20), nullable=True))
    op.add_column('node', sa.Column('longitude_2', sa.Float(precision=10, asdecimal=20), nullable=True))
    op.alter_column('path', 'end',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('path', 'end',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('node', 'longitude_2')
    op.drop_column('node', 'latitude_2')
    # ### end Alembic commands ###
