"""empty message

Revision ID: b289df99ea2f
Revises: c3e8eba33ec7
Create Date: 2021-04-20 14:20:07.940589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b289df99ea2f'
down_revision = 'c3e8eba33ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'description')
    # ### end Alembic commands ###
