"""empty message

Revision ID: c3e8eba33ec7
Revises: 964b6d8f0372
Create Date: 2021-04-20 14:07:06.189905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e8eba33ec7'
down_revision = '964b6d8f0372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'path', 'node', ['end'], ['node_id'])
    op.create_foreign_key(None, 'path', 'node', ['start'], ['node_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'path', type_='foreignkey')
    op.drop_constraint(None, 'path', type_='foreignkey')
    # ### end Alembic commands ###
