"""empty message

Revision ID: dc9be99f3298
Revises: 
Create Date: 2021-04-24 18:52:52.627140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9be99f3298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address1', sa.Text(), nullable=True),
    sa.Column('address2', sa.Text(), nullable=True),
    sa.Column('address3', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('b_type', sa.String(length=20), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.Column('longitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.PrimaryKeyConstraint('building_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.Column('longitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.Column('latitude_2', sa.Float(precision=10, asdecimal=20), nullable=True),
    sa.Column('longitude_2', sa.Float(precision=10, asdecimal=20), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('object_detection_objects',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('object_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.Column('longitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('object_name')
    )
    op.create_table('starting_points',
    sa.Column('sp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.Column('longitude', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.PrimaryKeyConstraint('sp_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('map_areas',
    sa.Column('map_area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('point1', sa.Integer(), nullable=False),
    sa.Column('point2', sa.Integer(), nullable=False),
    sa.Column('point3', sa.Integer(), nullable=False),
    sa.Column('point4', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point1'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['point2'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['point3'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['point4'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('map_area_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('paths',
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('map_area', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(precision=10, asdecimal=20), nullable=False),
    sa.ForeignKeyConstraint(['end'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['map_area'], ['map_areas.map_area_id'], ),
    sa.ForeignKeyConstraint(['start'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('path_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paths')
    op.drop_table('map_areas')
    op.drop_table('events')
    op.drop_table('starting_points')
    op.drop_table('object_detection_objects')
    op.drop_table('nodes')
    op.drop_table('buildings')
    # ### end Alembic commands ###
