"""empty message

Revision ID: 1f0630f74450
Revises: 
Create Date: 2021-03-21 16:15:15.278629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f0630f74450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('longitude', sa.Float(precision=10, asdecimal=20), nullable=False))
    op.drop_column('buildings', 'longtitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('longtitude', mysql.FLOAT(), nullable=False))
    op.drop_column('buildings', 'longitude')
    # ### end Alembic commands ###
