name: Docker Image CI

on:
  push:
    branches: [ docker_deploy ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_DRIVER: overlay
        HEROKU_APP_NAME: uwi-ar-maps
        HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web 

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --tag $HEROKU_REGISTRY_IMAGE --file Dockerfile "."
        
      - name: Login to registry
        run: docker login -u _ -p ${{ secrets.HEROKU_AUTH_TOKEN }} registry.heroku.com
        
      - name: Push image to registry
        run: docker push $HEROKU_REGISTRY_IMAGE
        
